### ISSUE TITLE
What is an extension?

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-extension#31]
The [spec abstract](https://w3c.github.io/html-extensions/) says:
"This document provides a reference to all HTML extension specifications. Those specifications extend the HTML markup language by introducing new HTML elements, attributes, or attribute values. An [applicable extension specification](https://www.w3.org/TR/html51/infrastructure.html#applicable-specification) may define a new feature, prohibit certain otherwise conforming features, or may change the semantics, DOM mappings, or other processing rules for features defined in the [HTML specification](https://www.w3.org/TR/html/)."

We have a number of specifications included ranging from those that are closely associated with HTML (like [CSS Style Attributes](https://www.w3.org/TR/css-style-attr/)), to those that intentionally extend HTML (like [HTML Media Capture](https://www.w3.org/TR/html-media-capture/)).

It would be good to agree on a definition for an "HTML extension", before this Note progresses. Is it:

* A specification that is used in conjunction with HTML;
* A specification intentionally designed to extend HTML;
* Something else?

**Comment by chaals** [comment]
Good questions - but I am not convinced that we need to answer them exhaustively before we can produce a useful document. 

The value i see for the document is to enable people to find the things they think are part of HTML, whether from half-remembering something, seeing something used and wondering where it comes from, or wanting to know what others might expect their HTML processor - be it conformance checker, browser, authoring tool, or whatever - to handle.

That said…

There are a set of "extensions" defined in the sections on obsolete features - for example the specification still describes what appcache does, even though it isn't "part of HTML".

I think the following definitely are HTML extension specifications

* A specification that defines elements to be used in HTML (e.g. moving `ruby` into an external specification`)
* A specification that defines attributes to be used in HTML (e.g. microdata and RDFa)
* A specification that defines specific values for HTML attributes (e.g. for the `rel` attribute)
* A specification that defines changes to processing or conformance which affect an element, attribute or API defined in the HTML specificaiton (e.g. microdata currently specifies what amount to authoring conformance requirements by making changes to the content models of certain elements).

I *suspect* that a specification which extends an API defined in HTML is an extension, although it feels somehow different. There are a number of specs which extend the `navigator` object defined by HTML e.g. #9, #11, #12, #15, #18, #21 or the `HTMLMediaElement` e.g. #16, #17, #20, #21 (again). If a spec redefines processing steps, I think it is an extension. If it adds behaviour on an interface, I think it is *probably* an extension.

Another kind of case is MathML and SVG. The HTML specification describes how these extend HTML, and also defines effective changes to the stand-alone specifications - declaring elements or attributes invalid or changing their processing, and so on. I think these are extensions, although they should be described differently...

Then there are cases like the various DOM and URL specifications. HTML doesn't actually change these significantly, as far as I recall in 2 seconds of pretending to think, and in any case they don't actually change HTML - I think these are fine as normative references and are not really extensions.

**Comment by paulbrucecotton** [comment]
>I suspect that a specification which extends an API defined in HTML is an extension

I recommend that you review [Plan 2014](https://dev.w3.org/html5/decision-policy/html5-2014-plan.html#modularity)'s discussion of Modularity since it lists a large number of "extensions" of HTML.  Since the community has accepted that definition for some time I feel it would be inappropriate to create a new and different definition.

The bottom line is that specs like MSE and EME are definitely "extension specs" in my view.

/paulc

**Comment by chaals** [comment]
@paulbrucecotton, I had a look. The definition I found is

> HTML ... allows extension specs to define new elements, new attributes, new values for attributes that accept defined sets of keywords, and new APIs.

I think that's close to the definition I put into the list above - except that rather than "a new API" my version is slightly more restricted to something that directly touches an API defined in the HTML spec.

And yes, by those definitions, MSE, EME, and the host of specs that are currently noted in the issues as extending the `navigator object, which is defined in the HTML spec, are all "HTML extensions", which seems entirely reasonable to me.

While I am thinking about it, an implicit constraint I was thinking is that we should be listing things that are active deliverables of Working Groups, as a very approximate shorthand for "we have a reasonable expectation that these will get implemented"... and because tracking everything that the world is doing seems like a good way to make sure this thing doesn't get done enough to be published...

**Comment by paulbrucecotton** [comment]
>we should be listing things that are active deliverables of Working Groups

That seems like a reasonable goal since any user or organization can extend the HTML specification by:

a) using one of the defined [extension points](http://www.w3.org/TR/html5/single-page.html#extensibility), or
b) creating an [applicable specification](http://www.w3.org/TR/html5/single-page.html#other-applicable-specifications)
and then requiring the use of one of the above.  I really doubt that you want to track these kinds of extensions.

/paulc
